### ISSUE TITLE
RTSP_STREAM_BLACKLIST_ENABLED=false

### ISSUE THREAD

**Issue by lstday** [Roverr/rtsp-stream#43]
Causes unworkable app:
```
[user@laptop ~]$ docker run -d  -e RTSP_STREAM_BLACKLIST_ENABLED=false --name stream -p 80:8080 roverr/rtsp-stream:2
3f8f87d72fc1eaa729e6086aa0a76df0737d5f0da556be3a3351a3017f1cfb12
curl -d  '{ "uri": "rtsp://freja.hiof.no:1935/rtplive/definst/hessdalen03.stream" }' -X POST http://localhost:80/start
curl: (52) Empty reply from server
[user@laptop ~]$ docker logs stream 
time="2020-05-19T20:34:43Z" level=info msg="list endpoint enabled | MainProcess"
time="2020-05-19T20:34:43Z" level=info msg="start endpoint enabled | MainProcess"
time="2020-05-19T20:34:43Z" level=info msg="static endpoint enabled | MainProcess"
time="2020-05-19T20:34:43Z" level=info msg="stop endpoint enabled | MainProcess"
time="2020-05-19T20:34:43Z" level=info msg="rtsp-stream transcoder started on 8080 | MainProcess"
2020/05/19 20:34:50 http: panic serving 172.18.0.1:58230: runtime error: invalid memory address or nil pointer dereference
goroutine 8 [running]:
net/http.(*conn).serve.func1(0xc000174000)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x7fadc0, 0xb9e600)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/Roverr/rtsp-stream/core.(*Controller).StartStreamHandler(0xc0000a47e0, 0x903020, 0xc0001500e0, 0xc00017a000, 0x0, 0x0, 0x0)
        /go/src/github.com/Roverr/rtsp-stream/core/controller.go:388 +0x26e
github.com/Roverr/rtsp-stream/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0000a4780, 0x903020, 0xc0001500e0, 0xc00017a000)
        /go/src/github.com/Roverr/rtsp-stream/vendor/github.com/julienschmidt/httprouter/router.go:387 +0xa3d
github.com/Roverr/rtsp-stream/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x903020, 0xc0001500e0, 0xc00017a000)
        /go/src/github.com/Roverr/rtsp-stream/vendor/github.com/rs/cors/cors.go:219 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc00000e0c0, 0x903020, 0xc0001500e0, 0xc00017a000)
        /usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc000150000, 0x903020, 0xc0001500e0, 0xc00017a000)
        /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000174000, 0x903ca0, 0xc0000141c0)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
[user@laptop ~]$ curl -d  '{ "uri": "rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov" }' -X POST http://localhost:80/start
curl: (52) Empty reply from server

```

**Comment by Roverr** [comment]
Hi @lstday ,

Thanks for your report, I think I know what is wrong, I will try to create a fix soon.
